chatwork/charts

php/templates/ingress.yaml, php/values.yaml
https://chatwork.atlassian.net/browse/STRIX-36
* 緊急メンテナンスのように一時的に path を追加する場合を想定して、`preferPaths` を追加。
* `preferPaths` で指定した path は、上位に登録されるのでこちらが優先となる。
`helm template` で出力されたマニフェストで確認。
* `preferPaths` なし
```
$ helm template --set "ingress.patht=/*" --set ingress.port=8000 --set ingress.enabled=true --set "ingress.hosts[0]=www.example.com" -x templates/ingress.yaml --name php .
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: php
labels:
app: php
chart: php-0.5.0
release: php
heritage: Tiller
spec:
rules:
- host: www.example.com
http:
paths:
- path:
backend:
serviceName: php
servicePort: 8000
```
* `preferPaths` あり
```
helm template --set "ingress.path=/*" --set ingress.port=8000 --set ingress.enabled=true --set "ingress.hosts[0]=www.example.com" --set …
```
=> STRIX-36: Ingress に preferPaths を追加

regcred/Chart.yaml, regcred/README.md, regcred/templates/secret.yaml
```
$ helm install --name xxx ... chatwork/regcred
```
Fix to be able to create a secret with the specified name `xxx`.
=> [regcred] Changed to use specified name

slime/.helmignore, slime/Chart.yaml, slime/Makefile, slime/README.md, slime/templates/_helpers.tpl, slime/templates/configmap.yaml, slime/templates/secret.yaml, slime/values.yaml
₍Ꙭ̂₎ < Not my bad slime
We may need a specific Kubernetes Resouce.
For example in nginx-ingress when defining secret for TLS in helmfile.
So we have made Slime Chart to make a simple Kubernetes Resource to solve the problem.
Note: We do not place importance on building services like cloudposse/monochart. Slime only fills the gap.
Now only `ConfigMap` and `Secrets` support.
Other resources will be supported when needed.
=> add slime chart

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/templates/ingress.yaml, php/templates/service.yaml, php/templates/test/test-pod.yaml, php/values.yaml
Support `service.extraPorts`.
It is used for applications that expose multiple ports (e.g. 80/443) as use cases.
=> [php] add service extra port

php/README.md, php/templates/deployment.yaml, php/values.yaml
This PR adds support for valueFrom key in fpm.extraEnv.
* example(values.yaml)
```
fpm:
extraEnv:
- name: HOST_IP
valueFrom:
fieldRef:
fieldPath: status.hostIP
```
=> [php] change type of fpm.extraEnv to YAML list

postfix/Makefile, postfix/templates/dev-mailcatcher.yaml, postfix/templates/test/test-pod-mailcatcher.yaml, postfix/templates/test/test-pod.yaml, postfix/values.yaml
This PR replaces MailHog with MailCatcher.
Because MailHog Web UI can not display iso-2022-jp encoded mail correctly.
MailCatcher Web UI can display it correctly.
=> [postfix] replace MailHog with MailCatcher

php/Chart.yaml, php/README.md, php/templates/ingress.yaml
Ingress supports multiple hosts for domain routing with NGINX.
NOTE: Domain routing should be resolved in ingress. 
However, Ingress has many limitations. However, because I have many limitations in ingress, I do routing with NGINX.
=> [php] support ingress multi host

php/README.md, php/templates/deployment.yaml, php/values.yaml
This PR adds `fpm.command` to customize command in the php-fpm image.
You can use it to override command for the fpm container, as shown below.
```sh
$ helm template --name php . > default.yaml
$ helm template --set "fpm.command[0]=php-fpm" --set "fpm.command[1]=-dzend_extension=xdebug.so" --name php . > command_customized.yaml
$ diff -u default.yaml command_customized.yaml
--- default.yaml        2019-06-12 15:38:19.000000000 +0900
+++ command_customized.yaml     2019-06-12 16:05:18.000000000 +0900
@@ -814,6 +814,10 @@
- name: "php-fpm"
image: "php:7.1-fpm-alpine"
imagePullPolicy: IfNotPresent
+        command:
+        - php-fpm
+        - -dzend_extension=xdebug.so
+
lifecycle:
preStop:
exec:
```
=> [php] add fpm.command

php/templates/configmap-fpm.yaml
The indent was broken. This PR fix it.
=> [php] fix wrong indent in configmap-fpm.yaml

php/Chart.yaml, php/values.yaml
The evaluation result of `print "%t"` becomes `%t`.
This is a mistake and we should use `printf` correctly.
=> [php] fixes type check

elasticmq/templates/deployment.yaml, elasticmq/values.yaml
This PR allows to inject extra volumes and volumeMounts.
Here is an example of how to use the added values.
```bash
$ helm template --name elasticmq . > a.yaml
$ helm template --name elasticmq --set extraVolumes\[0\].name=data --set extraVolumes\[0\].mountPath=/data --set extraVolumeMounts\[0\].name=data --set extraVolumeMounts\[0\].path=/mount/data . > b.yaml
$ diff -u a.yaml b.yaml
--- a.yaml      2019-09-11 17:40:24.000000000 +0900
+++ b.yaml      2019-09-11 17:40:14.000000000 +0900
@@ -134,8 +134,14 @@
- name: conf
subPath: elasticmq_conf
mountPath: /opt/elasticmq.conf
+            - name: data
+              path: /mount/data
+
volumes:
- name: conf
configMap:
name: elasticmq
+        - mountPath: /data
+          name: data
+
```
=> [elasticmq] add extraVolumes and extraVolumeMounts

php/templates/deployment.yaml, php/values.yaml
This PR allows to add postStart commands to nginx and fpm pods.
Example of execution is below.
```
$ helm template --name php . > a.yaml
$ helm template \
--set nginx.lifecycle.postStart\[0\]="/bin/sh" \
--set nginx.lifecycle.postStart\[1\]="-c" \
--set nginx.lifecycle.postStart\[2\]="echo 'nginx'" \
--set fpm.lifecycle.postStart\[0\]="/bin/sh" \
--set fpm.lifecycle.postStart\[1\]="-c" \
--set fpm.lifecycle.postStart\[2\]="echo 'fpm'" \
--name php . > b.yaml
$ diff -u a.yaml b.yaml
--- a.yaml      2019-11-06 12:56:50.000000000 +0900
+++ b.yaml      2019-11-06 12:56:55.000000000 +0900
@@ -798,6 +798,13 @@
timeoutSeconds: 1
lifecycle:
+          postStart:
+            exec:
+              command:
+              - /bin/sh
+              - -c
+              - echo 'nginx'
+
preStop:
exec: …
```
=> [php] add postStart to nginx and fpm

php/values.yaml
Matched the value of the item `fpm.ini` to the criteria of the expression
```
{{- if eq (printf "%t" $v) "true" }}
php_flag[{{ snakecase $k }}] = on
{{- else if eq (printf "%t" $v) "false" }}
php_flag[{{ snakecase $k }}] = off
```
=> modify the flag value "off" => "false"

php/templates/configmap-fpm.yaml, php/templates/deployment.yaml, php/values.yaml
`php.ini` was made because PHP error is not output to standard error output.
Only the following items are set.
- display_errors
- error_reporting
- expose_php
If you want to add other items, add them to `.values.fpm.ini`. And they are added to `php.ini`
The PHP chart did not show any PHP errors to logs.
```
helm install php .
kubectl exec php-949b58d77-2kw6m -c php-fpm  -- sh -c "echo \"<?php\na();\" > /var/www/html/error.php"
kubectl exec -it php-949b58d77-2kw6m -c php-fpm /bin/sh
/var/www/html # curl http://localhost/error.php
kubectl logs php-949b58d77-2kw6m -c php-fpm
[20-Nov-2019 06:30:54] NOTICE: fpm is running, pid 1
[20-Nov-2019 06:30:54] NOTICE: ready to handle connections
```
This PR resolved it.
```
helm install php .
kubectl exec php-6c4fb59864-p2dtk -c php-fpm  -- sh -c "echo …
```
=> Create phpini file

twistlock-console/Chart.yaml, twistlock-console/Makefile, twistlock-console/README.md, twistlock-console/templates/_helpers.tpl, twistlock-console/templates/configmap.yaml, twistlock-console/templates/deployment.yaml, twistlock-console/templates/ingress.yaml, twistlock-console/templates/persistentvolumeclaim.yaml, twistlock-console/templates/secrets.yaml, twistlock-console/templates/service.yaml, twistlock-console/templates/serviceaccount.yaml, twistlock-console/twistlock.org.cfg, twistlock-console/values.yaml, twistlock-defender/Chart.yaml, twistlock-defender/Makefile, twistlock-defender/README.md, twistlock-defender/templates/_helpers.tpl, twistlock-defender/templates/clusterrole.yaml, twistlock-defender/templates/clusterrolebinding.yaml, twistlock-defender/templates/daemonset.yaml, twistlock-defender/templates/deployment.yaml, twistlock-defender/templates/secret.yaml, twistlock-defender/templates/serviceaccount.yaml, twistlock-defender/values.yaml
- twistlock console, defender chart
- document: https://docs.twistlock.com/docs/
- You need access token...
- You can install defender with daemonset or deployment
- Default is daemonset.
- An access token is also required to pull image, the test cannot be performed and `Makefile` is dummy.
=> SRE-1226: twistlock chart

twistlock-console/Chart.yaml, twistlock-console/README.md, twistlock-console/templates/deployment.yaml, twistlock-console/values.yaml, twistlock-defender/Chart.yaml, twistlock-defender/README.md, twistlock-defender/templates/daemonset.yaml, twistlock-defender/templates/deployment.yaml, twistlock-defender/values.yaml
- Bump chart version
- Add prove for twistlock-console and defender
- The defender seems to have no items to check, but it can be added later.
=> SRE-1226: Add prove to twistlock charts

.circleci/check-version.sh, .circleci/config.yml, .github/pull_request_template.md
This PR adds a checker into ci. The checker does confirm whether it updates the chart version was bumped and cause an error if the chart version didn't bump. As a result, we can prevent to merge the chart didn't bump version.
- PASSED: bumped the version 
https://github.com/chatwork/charts/compare/check-version-was-bumped...50f900c
https://circleci.com/gh/chatwork/charts/903
```
========================================
[php] diff version
-version: 0.13.3
+version: 0.13.4
========================================
```
- FAILED: did not change the version 
https://github.com/chatwork/charts/compare/check-version-was-bumped...ab8f24a
https://circleci.com/gh/chatwork/charts/904
```
========================================
[php] diff version
========================================
You must bump …
```
=> [ci] check the chart version was bumped

postfix/Chart.yaml, postfix/templates/test/test-pod-mailcatcher.yaml
https://github.com/chatwork/charts/blob/master/postfix/templates/daemonset.yaml#L48-L53
If `hostNetwork` is enabled with `hostPort` omitted, access is made with `containerPort` 25.
However, the `hostPort` was required for testing.
=> [postfix] fixes use only hostNetwork in mailcatcher tests

php/Chart.yaml, php/templates/service.yaml
The problem that YAML breaks
**values.yaml**
```
nginx:
extraPorts:
- name: health
containerPort: 7777
protocol: TCP
```
**result**
```yaml
spec:
type: ClusterIP
ports:
- name: health
port: 7777protocol: TCP
targetPort: health
```
=> [php] fixes YAML was broken by service extraPorts

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
Enabled `serviceAccountName` to run PHP Chart on EKS.
=> [php] support exists serviceaccount

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
IRSA must be supported for php chart to work with EKS.
```
$ ls -la /var/run/secrets/eks.amazonaws.com/serviceaccount/..2019_12_10_15_33_09.833408446/token
-rw------- 1 root root 1034 Dec 10 15:33 /var/run/secrets/eks.amazonaws.com/serviceaccount/..2019_12_10_15_33_09.833408446/token
```
Only root users can read and write tokens mounted with IRSA.
However, in PHP-FPM, it should be executed as the nobody user, and the token cannot be referenced from the nobody user.
https://docs.aws.amazon.com/en_pv/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
So we will modify the `SecurityContext` based on this document.
=> [php] support securityContext

postfix/Chart.yaml, postfix/templates/configmap.yaml, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/values.yaml
I have a use case that uses `sender_dependent_relayhost_maps`.
For that reason, it was changed so that files could be placed in the postfix directory.
=> [postfix] change to be able to put other files in postfix directory

postfix/Chart.yaml, postfix/templates/secret.yaml, postfix/values.yaml
Supported `tpl` with `sasl_passwd` to use helmfile  vals.
**values.yaml**
```
postfix:
secrets:
sasl_passwd: |
[smtp.sendgrid.net]:587 {{ .Values.username }}:{{ .Values.password }}
username: sendgrid-user
passowrd:  ref+awsssm://path/to/password?region=ap-northeast-1
```
=> [postfix] support tpl for secrets

php/Chart.yaml, php/values.yaml
Removed `replicaCount` from default values
Because the scaled replicas of the deployment are forced to default values.
=> [php] removed replicaCount from default values

newrelic-php-agent/Chart.yaml, newrelic-php-agent/values.yaml
Newrelic's PHP Agent version 9.6.1.256 has been released, so it corresponds
https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-961256
=> version up v9.4.0.249 => v9.6.1.256

php/Chart.yaml, php/README.md, php/values.yaml
Upgrade dependent container versions.
- nginx v1.15.1 -> 1.17
- php-fpm v7.1 -> 7.4
- Update `php.ini`, `php-fpm.conf`, `www.conf`
- Description of PHP-FPM log option added from v7.3
=> [php] update nginx and php-fpm version

postfix/Chart.yaml, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/templates/statefulset.yaml, postfix/values.yaml
Lifecycle can be injected because we want to add a waiting time after flushing `preStop`.
=> [postfix] supports lifecycle injection

php/Chart.yaml, php/templates/configmap-busybox.yaml, php/templates/configmap-fpm.yaml, php/templates/configmap-nginx.yaml, php/templates/deployment.yaml, php/templates/ingress.yaml, php/templates/secret-busybox.yaml, php/templates/secret-fpm.yaml, php/templates/secret-nginx.yaml, php/templates/service.yaml
https://github.com/helm/helm/issues/7704
In go-yaml used by helm, space is broken on lines that exceed `80` characters.
This has the problem of breaking the go template.
So, I changed to do `toYaml` after `tpl` expansion of annotations.
=> [php] fixes tpl expansion of annotations

fluent-bit/.helmignore, fluent-bit/Chart.yaml, fluent-bit/Makefile, fluent-bit/README.md, fluent-bit/templates/NOTES.txt, fluent-bit/templates/_helpers.tpl, fluent-bit/templates/cluster-role.yaml, fluent-bit/templates/cluster-rolebinding.yaml, fluent-bit/templates/configmap.yaml, fluent-bit/templates/daemonset.yaml, fluent-bit/templates/psp.yaml, fluent-bit/templates/secret.yaml, fluent-bit/templates/serviceaccount.yaml, fluent-bit/values.yaml
I made a helm chart of [Fluent Bit](https://fluentbit.io/).
There is a [stable/fluent-bit](https://github.com/helm/charts/tree/master/stable/fluent-bit), but it is difficult to support BigQuery, CloudWatch and S3, so I decided to create a new one.
=> add fluent-bit

fluent-bit/Chart.yaml, fluent-bit/README.md, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
For example, the extension of the command is necessary in the use case of a plugin as shown below.
```
$ /fluent-bit/bin/fluent-bit -e out_s3.so -c /fluent-bit/etc/fluent-bit.conf
```
=> [fluent-bit] add command

elasticsearch/.helmignore, elasticsearch/Chart.yaml, elasticsearch/Makefile, elasticsearch/templates/_helpers.tpl, elasticsearch/templates/configmap.yaml, elasticsearch/templates/deployment.yaml, elasticsearch/templates/service.yaml, elasticsearch/templates/test/test-pod.yaml, elasticsearch/values.yaml
This PR is that added an Elasticsearch Chart.
This chart implements only the minimum functionality needed to use Elasticsearch for development and testing (including CI).
=> [elasticsearch] add Elasticsearch chart

fluent-bit/Chart.yaml, fluent-bit/README.md, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
- Add `priorityClassName` to fluent-bit chart
- https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
=> Add priorityClassName to fluent-bit

postfix/Chart.yaml, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/templates/statefulset.yaml, postfix/values.yaml
Added exporter so that postfix chart can get metrics.
By default, [kumina-postfix-exporter](https://github.com/kumina/postfix_exporter) is used.
=> [postfix] support metrics

fluentd/.helmignore, fluentd/Chart.yaml, fluentd/Makefile, fluentd/README.md, fluentd/examples/daemonset.yaml, fluentd/examples/statefulset.yaml, fluentd/examples/use-udp.yaml, fluentd/templates/NOTES.txt, fluentd/templates/_helpers.tpl, fluentd/templates/cluster-role.yaml, fluentd/templates/cluster-rolebinding.yaml, fluentd/templates/configmap.yaml, fluentd/templates/daemonset.yaml, fluentd/templates/psp.yaml, fluentd/templates/pvc.yaml, fluentd/templates/secret.yaml, fluentd/templates/service-extra.yaml, fluentd/templates/service-forward.yaml, fluentd/templates/service-http.yaml, fluentd/templates/serviceaccount.yaml, fluentd/templates/statefulset.yaml, fluentd/values.yaml
Added a chart for `fluentd`.
There are other published fluentd charts, but none of them have the problem of not being able to use the official docker image and not being able to define config freely, so I created a new one.
=> [fluentd] add fluentd

newrelic-php-agent/Chart.yaml, newrelic-php-agent/README.md, newrelic-php-agent/templates/daemonset.yaml, newrelic-php-agent/templates/deployment.yaml, newrelic-php-agent/values.yaml
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
Priority classes are now supported.
This is to solve a problem where a `DaemonSet` wouldn't work with a large number of pods on a node.
=> [newrelic-php-agent] add priority class

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/pod-conditions/
Added support for `readinessGates` for rolling updates with no downtime when using alb Ingress.
=> [php] add readinessGates

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
Support for the option not to mount the default template.
It makes it easier to use use cases that prioritize configuration files included in containers.
=> [php] support for the option not to mount the default template

php/Chart.yaml, php/README.md, php/templates/_helpers.tpl, php/templates/psp.yaml, php/values.yaml
Fixes to allow you to change the details on the PSP.
Changes:
- Change to create RBAC and not create PSP
- Fixed to allow you to change the name and various items
**NOTE: PSP was created with `rbac.create:true`, but it has been braked changed so that PSP is not created unless it is `psp.create:true`.**
=> [php] fixes to allow you to change the details on the PSP

php/Chart.yaml, php/README.md, php/templates/NOTES.txt, php/templates/_helpers.tpl, php/templates/autoscaling.yaml, php/templates/configmap-busybox.yaml, php/templates/configmap-fpm.yaml, php/templates/configmap-nginx.yaml, php/templates/deployment.yaml, php/templates/extras.yaml, php/templates/ingress.yaml, php/templates/pdb.yaml, php/templates/psp.yaml, php/templates/role.yaml, php/templates/rolebinding.yaml, php/templates/secret-busybox.yaml, php/templates/secret-fpm.yaml, php/templates/secret-nginx.yaml, php/templates/service.yaml, php/templates/serviceaccount.yaml, php/templates/test/test-pod.yaml, php/values.yaml
For PHP v1, we made some simplifying changes to the specifications. 
**Breaking Change**
- Changed to expand `tpl` only in ConfigMap/Secret
-A key name for the `values.yaml` has been altered 
- `psp` -> `podSecurityPolicy`
- `busybox.disabledDefaultTemplatesMount` -> `busybox.enableAutoMountConfigMap`
- `busybox.templates` -> `busyboxy.configMaps`
- `ingress.preferPaths` -> `ingress.hosts.extraPaths`
- Changed to ignore `replicaCount` when Autoscaling is enabled
- Changed the naming scheme for ConfigMap/Secret
- Change the version of ingress to match kubernetes version
- Specify the `ingress.overrideApiVersion` if you want to use a specific version of ingress API
- Changed to allow you to specify the path of Ingress
- Change to specify PSP use for Rule rule only when PSP is enabled
- …
=> [php] v1.0.0

php/Chart.yaml, php/README.md, php/values.yaml
Removed the default value in NGINX Readines/Liveness/Startup Probe.
This is because NGINX does not allow you to remove probe.
=> [php] remove default probe

aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/README.md, aws-ebs-csi-driver/templates/controller.yaml, aws-ebs-csi-driver/values.yaml
- bump some versions
- modified csi-provisioner parameter for v2
- https://github.com/kubernetes-csi/external-provisioner/releases
-  The v1 version of csi-provisinor is compatible up to 1.18, so change to v2.
=> [aws-ebs-csi-driver]Update containers

akka/Makefile, argoproj-crd/Makefile, aws-alb-ingress-controller/Makefile, aws-ebs-csi-driver/Makefile, aws-secret-operator/Makefile, burrow/Makefile, contour/Makefile, dynamodb/Makefile, elasticmq/Makefile, elasticsearch/Makefile, example/Makefile, fluent-bit/Makefile, fluentd/Makefile, gcp-credentials/Makefile, kube-schedule-scaler/Makefile, mailcatcher/Makefile, newrelic-php-agent/Makefile, php/Makefile, postfix/Makefile, raw/Makefile, regcred/Makefile, slime/Makefile, twistlock-console/Makefile, twistlock-defender/Makefile
```
$ kubeval --help
Validate a Kubernetes YAML file against the relevant schema
Usage:
kubeval <file> [file...] [flags]
Flags:
--additional-schema-locations strings   Comma-seperated list of secondary base URLs used to download schemas
-d, --directories strings                   A comma-separated list of directories to recursively search for YAML documents
--exit-on-error                         Immediately stop execution when the first error is encountered
-f, --filename string                       filename to be displayed when testing manifests read from stdin (default "stdin")
--force-color                           Force colored output even if stdout is not a TTY
-h, --help                                  help for kubeval
--ignore-missing-schemas                Skip validation for …
```
=> enable the --strict option in kubeval

php/Chart.yaml, php/templates/_helpers.tpl, php/templates/ingress.yaml
**support ingress v1 for kubernetes 1.19**
addressed the following changes
- `apiVersion`
- `backend.service`
- https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules 
- https://github.com/kubernetes/kubernetes/pull/89778
=> [php] support ingress v1

mysql/Chart.yaml, mysql/templates/tests/test.yaml
This [PR](https://github.com/helm/charts/pull/23075/files
) caused the test to fail when the root user password was specified. Since the test only runs when the root password is specified, the CI passed on helm/charts repo.
- Run the test in a container with MySQL client installed
```
$ helm install mysql ./ --set mysqlRootPassword=secret
$ helm test mysql
NAME: mysql
LAST DEPLOYED: Fri Mar  5 18:26:31 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     mysql-test
Last Started:   Fri Mar  5 18:26:47 2021
Last Completed: Fri Mar  5 18:26:49 2021
Phase:          Failed
...
$ kubectl logs mysql-test
1..1
not ok 1 Testing MySQL Connection
```
```
$ helm test mysql
NAME: mysql
LAST DEPLOYED: Fri Mar  5 18:25:43 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: …
```
=> [mysql] Fix helm test mysql

php/Chart.yaml, php/templates/ingress.yaml
- add pathType param for ingress v1
- pathType has been required since v1
- https://github.com/kubernetes/kubernetes/pull/89778   
- > * `pathType` no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
- value (`ImplementationSpecific`) is set to the same as the default value in 1.18(v1beta1).
=> [PHP] add pathType param for ingress v1

akka/Chart.yaml, akka/templates/ingress-http.yaml
- add pathType param for ingress v1
- pathType has been required since v1
- https://github.com/kubernetes/kubernetes/pull/89778   
- > * `pathType` no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
- value (`ImplementationSpecific`) is set to the same as the default value in 1.18(v1beta1). 
-
=> [akka] add patyType param for Ingress v1

akka/README.md
livenessProbe, startupProbe, readinessProbeのsuccessThresholdの説明が間違ってたので修正
=> [akka] Modify Akka Chart README of some probe type successThreshold

docker-registry/Chart.yaml, docker-registry/README.md, docker-registry/templates/tests/test-pod.yaml, docker-registry/values.yaml
- The url for the test was fixed, so change it to `fullname`.
- add initContainer in test
- Because an error will occur if the name cannot be resolved reliably.
=> [docker-registy]modify test url

akka/Chart.yaml, akka/README.md, akka/templates/deployment.yaml, akka/values.yaml
- akka charts に`revisionHistoryLimit`(ReplicaSet を残す最大数)を設定できるようにする
- `revisionHistoryLimit`を設定できるように
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#deployment-v1-apps
=> ReplicaSet を残す数を設定できるようにする

postfix/Chart.yaml, postfix/templates/_helpers.tpl, postfix/templates/service.yaml
- fix service template for daemonset
- FYI: https://github.com/DataDog/helm-charts/commit/920dd74aa847085c62dd4521613cdce0b52adc44
With `internalTrafficPolicy: Local`, it is possible to use postfix-daemonset on the same node via service, so we do not need to set `hostNetwork` to true for postfix-daemonset.
=> fix svc for daemonset

akka/Chart.yaml, akka/templates/autoscaling.yaml, php/Chart.yaml, php/templates/autoscaling.yaml
- change autoscaling v2 condition
- Fixed because `.Capabilities.KubeVersion.GitVersion` is easier to use than `.Capabilities.APIVersions.Has`.
=> Update autoscaling v2 condition

php/Chart.yaml, php/README.md, php/values.yaml
A warning occurs when autoscaling is set.
```
coalesce.go:220: warning: cannot overwrite table with non table for php.autoscaling.metrics (map[])
```
This warning occurred because I set a value that did not match the type in `values.yaml`.
=> [php] fixes default values

postfix/Chart.yaml, postfix/templates/_helpers.tpl, postfix/templates/service.yaml, postfix/values.yaml
- fix internalTrafficPolicy condition
- not to enforce it just because of daemonset.
- comment out `hostPort`
=> [postfix]fix internalTrafficPolicy condition and comment out hostPort in values.yaml

php/Chart.yaml, php/templates/_helpers.tpl
- remove Pod Security Policy because it was removed from Kubernetes 1.25.
=> [php]remove psp from kubernetes version 1.25

argoproj-crd/Chart.yaml, argoproj-crd/README.md, argoproj-crd/ci.yaml, argoproj-crd/templates/applications.yaml, argoproj-crd/values.yaml
- https://github.com/argoproj/argo-cd/pull/9755
=> [argoproj-crd]update application for each namespace

slime/Chart.yaml, slime/examples/cronjob-advanced.yaml, slime/templates/cronjob.yaml, slime/values.yaml
The initContainers key used to be the same as the deployment key, so it is now separated.
```
$ kubectl -n chatwork get pod
NAME                            READY   STATUS      RESTARTS   AGE
slime-advanced-28202505-7t26j   0/1     Completed   0          4m9s
slime-advanced-28202506-vnkrr   0/1     Completed   0          3m9s
slime-advanced-28202507-zsvzc   0/1     Completed   0          2m9s
slime-advanced-28202508-ljr4j   0/1     Completed   0          69s
slime-advanced-28202509-fpt4g   0/1     Completed   0          9s
$  kubectl -n chatwork logs  slime-advanced-28202502-ld6jt
Defaulted container "slime-advanced-job" out of: slime-advanced-job, slime-advanced-init (init)
Hello from Docker!
This message shows that your installation appears to be working correctly.
To generate this …
```
=> Fixed slime cronJob initContainers.

slime/Chart.yaml, slime/README.md, slime/examples/cronjob-additional-volumes.yaml, slime/examples/cronjob-extra-volumes.yaml, slime/templates/cronjob.yaml, slime/values.yaml
```
$ kubectl get cronjob cronjob-slime -o yaml
apiVersion: batch/v1
kind: CronJob
metadata:
annotations:
meta.helm.sh/release-name: cronjob
meta.helm.sh/release-namespace: default
creationTimestamp: "2023-11-09T07:31:34Z"
generation: 1
labels:
app.kubernetes.io/instance: cronjob
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: slime
helm.sh/chart: slime-1.3.0
name: cronjob-slime
namespace: default
resourceVersion: "8144359"
uid: 7d8b0341-9aed-4b54-98ce-17d3ce2d1f0b
spec:
concurrencyPolicy: Allow
failedJobsHistoryLimit: 1
jobTemplate:
metadata:
creationTimestamp: null
labels:
app.kubernetes.io/instance: cronjob
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: slime
helm.sh/chart: slime-1.3.0
spec:
template:
metadata:
creationTimestamp: null
labels: …
```
=> Support extra cronjob volumes.

php/Chart.yaml, php/templates/NOTES.txt, php/templates/ingress.yaml, php/values.yaml
This Pull Request introduces enhancements to the ingress configuration, enabling support for multiple paths per host and updating corresponding settings across NOTES.txt, ingress.yaml, and values.yaml files.
I applied the following PATCH to check the operation.
```diff
$ git diff
diff --git a/php/values.yaml b/php/values.yaml
index 1cb8676..9c6bcd3 100644
--- a/php/values.yaml
+++ b/php/values.yaml
@@ -52,20 +52,20 @@ ingress:
enabled: false
labels: {}
annotations: {}
-  hosts: []
-  # - host: localhost
-  #   paths:
-  #   - /foo
-  #   - /bar
+  hosts:
+  - host: localhost
+    paths:
+    - /foo
+    - /bar
-  tls: []
-  # - hosts:
-  #     - example.com
-  #       secretName: examplecret-tls
+  tls:
+  - hosts:
+    - example.com
+    secretName: examplecret-tls
ingressClassName: '' …
```
=> Updated ingress configuration and enabled multiple paths in ingress.yaml

akka/Chart.yaml, akka/templates/autoscaling.yaml, akka/templates/deployment.yaml, akka/templates/rollout.yaml, akka/values.yaml
- Change to allow setting 0 in the replicas of Deployment
- Revert the HPA Chart to the state before applying #300 
- Add HPA targeted at Rollout
=> Add HPA targeted at Rollout
