tiller/Chart.yaml, tiller/templates/deployment.yaml, tiller/templates/serviceaccount.yaml, tiller/templates/test/test-pod.yaml, tiller/values.yaml, tiller/values.yaml.sample
- role for tiller changed
- typo fixed(rback -> rbac)
=> modified role for tiller

tiller/Chart.yaml, tiller/Makefile, tiller/templates/_helpers.tpl, tiller/templates/deployment.yaml, tiller/templates/serviceaccount-client.yaml, tiller/templates/serviceaccount-tiller.yaml, tiller/templates/test/test-pod.yaml, tiller/values.yaml
- change test sa role
- cluster-admin authority is too strong
- change sa name 
- call variable defined in ```_helpers.tpl```
=> change serviceaccount name and test sa role

php/Chart.yaml, php/templates/deployment.yaml, php/values.yaml
=> [php] refctor Values.annotation -> Values.deployment.podAnnotation

php/Chart.yaml, php/Makefile, php/README.md, php/templates/configmap-busybox.yaml, php/templates/configmap-fpm.yaml, php/templates/configmap-nginx.yaml, php/templates/deployment.yaml, php/templates/ingress.yaml, php/templates/secret-busybox.yaml, php/templates/secret-fpm.yaml, php/templates/secret-nginx.yaml, php/templates/service.yaml, php/templates/test/test-pod.yaml, php/values.yaml
Added [README.md](https://github.com/chatwork/charts/blob/67f2a42a70e7e7dc3fe1e867e6484c8af9927589/php/README.md). And fixed consistency and complexity.
=> [php] Add README.md

assume-role-crd/Chart.yaml, assume-role-crd/templates/test/test-pod.yaml
- I modified test role and rolebinding for tiller-per-namespace which cannot create ```clusterrole``` and ```clusterrolebiding```
=> modified test role

Makefile, assume-role-crd/Chart.yaml, assume-role-crd/Makefile, assume-role-crd/templates/test/test-pod.yaml
- change test role to limit resource
- modified Makefile to work under tiller-per-ns in test
- modified Makefile for circleci to bump helm version
=> Modified test role and Makefile

dynamodb/.helmignore, dynamodb/Chart.yaml, dynamodb/Makefile, dynamodb/templates/_helpers.tpl, dynamodb/templates/deployment.yaml, dynamodb/templates/service.yaml, dynamodb/templates/test/test-pod.yaml, dynamodb/values.yaml
```
$ helm install --name dynamodb --set service.type=LoadBalancer  .
NAME:   dynamodb
LAST DEPLOYED: Tue Mar 19 10:54:06 2019
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Service
NAME      TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)         AGE
dynamodb  LoadBalancer  10.104.22.237  localhost    8000:32638/TCP  1s
==> v1/Deployment
NAME      DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
dynamodb  1        0        0           0          1s
==> v1/Pod(related)
NAME                       READY  STATUS   RESTARTS  AGE
dynamodb-7b7898c6bc-grzv5  0/1    Pending  0         1s
$ aws dynamodb list-tables --endpoint-url http://localhost:8000
{
"TableNames": []
}
```
```
$ helm template --name dynamodb . 
---
apiVersion: v1
kind: Service
metadata:
name: dynamodb
labels:
app: dynamodb …
```
=> add Dynamodb

elasticmq/.helmignore, elasticmq/Chart.yaml, elasticmq/Makefile, elasticmq/templates/_helpers.tpl, elasticmq/templates/configmap.yaml, elasticmq/templates/deployment.yaml, elasticmq/templates/service.yaml, elasticmq/templates/test/test-pod.yaml, elasticmq/values.yaml
```
$ helm install --name elasticmq --set service.type=LoadBalancer  .
NAME:   elasticmq
LAST DEPLOYED: Tue Mar 26 11:36:23 2019
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/ConfigMap
NAME       DATA  AGE
elasticmq  1     1s
==> v1/Service
NAME       TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)         AGE
elasticmq  LoadBalancer  10.111.167.123  localhost    9324:32651/TCP  1s
==> v1/Deployment
NAME       DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
elasticmq  1        1        1           0          1s
==> v1/Pod(related)
NAME                        READY  STATUS             RESTARTS  AGE
elasticmq-57786b8478-bdrdj  0/1    ContainerCreating  0         1s
$ aws sqs create-queue --queue-name test --endpoint-url http://localhost:9324
{
"QueueUrl": …
```
=> add elasticmq

tiller/README.md, tiller/values.yaml
=> [tiller] add README.md

guard/Chart.yaml, guard/README.md, guard/templates/deployment.yaml, guard/templates/sa.yaml, guard/templates/test/test-pod.yaml, guard/values.yaml
=> [guard] add doc & refactor

assume-role-crd/Chart.yaml, assume-role-crd/README.md, assume-role-crd/templates/test/test-pod.yaml, assume-role-crd/values.yaml
=> [assume-role-crd-add-doc] add doc & refactor

kube-aws-iam-controller/Chart.yaml, kube-aws-iam-controller/Makefile, kube-aws-iam-controller/README.md, kube-aws-iam-controller/templates/_helplers.tpl, kube-aws-iam-controller/templates/clusterrole.yaml, kube-aws-iam-controller/templates/clusterrolebinding.yaml, kube-aws-iam-controller/templates/crd.yaml, kube-aws-iam-controller/templates/deployment.yaml, kube-aws-iam-controller/templates/serviceaccount.yaml, kube-aws-iam-controller/templates/test/test-pod.yaml, kube-aws-iam-controller/values.yaml
- kube-aws-iam-controller : https://github.com/mikkeloscar/kube-aws-iam-controller
- sample manifest: https://github.com/mikkeloscar/kube-aws-iam-controller/tree/master/docs
=> Add kube-aws-iam-controller chart

kube-aws-iam-controller-crd/Chart.yaml, kube-aws-iam-controller-crd/Makefile, kube-aws-iam-controller-crd/README.md, kube-aws-iam-controller-crd/templates/_helpers.tpl, kube-aws-iam-controller-crd/templates/iamrole.yaml, kube-aws-iam-controller-crd/templates/test/test-pod.yaml, kube-aws-iam-controller-crd/values.yaml
- CRD chart for [kube-aws-iam-controller](https://github.com/mikkeloscar/kube-aws-iam-controller)
- sample CRD manifest: https://github.com/mikkeloscar/kube-aws-iam-controller#specifying-aws-iam-role-on-pods
=> add kube-aws-iam-controller-crd

assume-role-operator/Chart.yaml, assume-role-operator/Makefile, assume-role-operator/README.md, assume-role-operator/awsiamrole-crd-sample.yaml, assume-role-operator/settings-sample.yaml, assume-role-operator/templates/deployment.yaml, assume-role-operator/templates/test/test-pod.yaml, assume-role-operator/values.yaml, kube-aws-iam-controller/settings-sample.yaml
This chart has not `volumes` option. I need `volumes` and `volumeMounts` for [kube-aws-iam-controller](https://github.com/mikkeloscar/kube-aws-iam-controller/blob/master/docs/example-app.yaml).
- Add README.me
- Modified deployment.yaml
=> Modify assume role operator

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
release:
- https://github.com/chatwork/charts/pull/69
=> [PHP] release v0.10.0

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
It is difficult to write settings in 3 places when mounting on all containers.
So, prepare the setting in PHP chart. Settings for mounting on all containers and settings for mounting on each container.
=> [php] add extraVolumes and extraVolumeMounts

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
* https://github.com/chatwork/charts/pull/80
=> [php] release v0.13.0

php/Chart.yaml, php/templates/configmap-fpm.yaml
* https://github.com/chatwork/charts/pull/85
=> [php] v0.13.1

contour/Chart.yaml, contour/Makefile, contour/README.md, contour/templates/contour-deployment.yaml, contour/templates/envoy-daemonset.yaml, contour/templates/envoy-deployment.yaml, contour/templates/envoy-service.yaml, contour/templates/test/test-pod.yaml, contour/values.yaml
- add volume options
- modified values bug
- modified test
- ref: https://github.com/heptio/contour/blob/master/docs/troubleshooting.md#envoy-container-not-listening-on-port-8080-or-8443
=> Fix contour

contour/Chart.yaml, contour/templates/envoy-deployment.yaml
=> modified envoy deployment

kube-aws-iam-controller/Chart.yaml, kube-aws-iam-controller/README.md, kube-aws-iam-controller/templates/deployment.yaml, kube-aws-iam-controller/values.yaml
- remove `onMaster` flag
- `tolerations` and `affinity` instead of `onMaster`
- remove `nodeSelector` flag
- `affinity` instead of `nodeSelector`
=> modified kaic chart

assume-role-operator/Chart.yaml, assume-role-operator/README.md, assume-role-operator/templates/deployment.yaml
- as same https://github.com/chatwork/charts/pull/94
=> delete onMaster and nodeSelector

newrelic-php-agent/.helmignore, newrelic-php-agent/Chart.yaml, newrelic-php-agent/Makefile, newrelic-php-agent/README.md, newrelic-php-agent/templates/_helpers.tpl, newrelic-php-agent/templates/daemonset.yaml, newrelic-php-agent/templates/tests/test-pod.yaml, newrelic-php-agent/values.yaml
With this PR, you can use Newrelic's extension for PHP.
=> new relic php用Charts作成

dynamodb/Chart.yaml, dynamodb/templates/deployment.yaml, dynamodb/values.yaml
This PR allows you to inject values for envFrom from values.yaml.
=> [dynamodb] add envFrom

contour/Chart.yaml, contour/Makefile, contour/README.md, contour/crd.yaml, contour/templates/contour-clusterrole.yaml, contour/templates/contour-config.yaml, contour/templates/contour-deployment.yaml, contour/templates/contour-role.yaml, contour/templates/contour-rolebinding.yaml, contour/templates/envoy-daemonset.yaml, contour/templates/envoy-deployment.yaml, contour/tls/contour-tls.yaml, contour/values.yaml
- Modifed chart for contour 1.0
=> Contour for 1.0

contour/tls/contour-tls.yaml, contour/values.yaml
- remove rc tag for contour image 
- https://github.com/projectcontour/contour/releases/tag/v1.0.0
- modified cert-manager api for 0.11.0
- https://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.10-0.11.html
=> Tweak for contour

php/Chart.yaml, php/values.yaml
* https://github.com/chatwork/charts/pull/105
=> [php] v0.13.3

twistlock-console/Chart.yaml, twistlock-console/README.md, twistlock-console/templates/deployment.yaml, twistlock-console/templates/service.yaml, twistlock-console/values.yaml, twistlock-defender/Chart.yaml, twistlock-defender/README.md, twistlock-defender/templates/daemonset.yaml, twistlock-defender/templates/deployment.yaml, twistlock-defender/values.yaml
- Modified typo(livenss....)
- twistlock-console port name can be specified
- Change twistlock-console updateStrategy 
- `rollingUpdate` cannot start pod because it reads the same volume...😞
=> Modified typo and defined port name in values.yaml

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/values.yaml
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core
fixes `terminationGracePeriodSeconds` and  `restartPolicy`.
=> [php ] fixes terminationGracePeriodSeconds and  restartPolicy

gcp-credentials/Chart.yaml, gcp-credentials/README.md, gcp-credentials/values.yaml
- Change each value to `.Values`
=> Modified gpc-credentials chart

php/Chart.yaml, php/templates/deployment.yaml
=> [php] fixes securityContext

twistlock-console/Chart.yaml, twistlock-console/README.md, twistlock-console/templates/deployment.yaml, twistlock-console/values.yaml
- Modified `tolerations`
- Bump version
=> Modified twistlock-console

postfix/Chart.yaml, postfix/Makefile, postfix/templates/_helpers.tpl, postfix/templates/configmap.yaml, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/templates/dev-mailcatcher.yaml, postfix/templates/pdb.yaml, postfix/templates/pvc.yaml, postfix/templates/secret.yaml, postfix/templates/service.yaml, postfix/templates/statefulset.yaml, postfix/templates/test/test-pod-mailcatcher.yaml, postfix/templates/test/test-pod.yaml, postfix/values.yaml
Support kubernetes `StatefulSet`.
This uses EBS on EKS to prevent lost mail when scaling in.
NOTE: No test since `StatefulSet` does not work in CI
=> [postfix] support statefulset

postfix/Chart.yaml, postfix/templates/statefulset.yaml
=> [postfix] fixes typo

postfix/Chart.yaml, postfix/values.yaml
https://github.com/chatwork/dockerfiles/tree/master/postfix
Support image `v3.4.8`.
=> [postfix] support v3.4.8

contour/Chart.yaml, contour/templates/contour-config.yaml, contour/templates/contour-deployment.yaml, contour/templates/contour-sa.yaml, contour/templates/contour-service.yaml, contour/templates/envoy-daemonset.yaml, contour/templates/envoy-deployment.yaml, contour/templates/envoy-service.yaml, contour/values.yaml
- Fix how to annotations
- Fix labels
- Unable to unify with each template, so unify
- Add `loadBalancerSourceRanges` to service template
=> SRE-1274: Modified chart contour

php/Chart.yaml, php/README.md, php/templates/hpa.yaml, php/values.yaml
=> [php] Support HPA

php/Chart.yaml, php/README.md, php/templates/autoscaling.yaml, php/values.yaml
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#metrictarget-v2beta2-autoscaling
Fix to v2beta2 format.
=> [php] fixes v2beta2 format

php/Chart.yaml, php/templates/test/test-pod.yaml
https://github.com/chatwork/charts/pull/136
=> [php] fixes port variable name

postfix/Chart.yaml, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/templates/statefulset.yaml, postfix/values.yaml
=> [chatwork/postfix] fixed postfix chart

fluent-bit/Chart.yaml, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
=> [fluent-bit] fixes tag

twistlock-console/Chart.yaml, twistlock-console/README.md, twistlock-console/templates/configmap.yaml, twistlock-console/templates/deployment.yaml, twistlock-console/templates/ingress.yaml, twistlock-console/templates/persistentvolumeclaim.yaml, twistlock-console/templates/secrets.yaml, twistlock-console/values.yaml, twistlock-defender/Chart.yaml, twistlock-defender/README.md, twistlock-defender/templates/clusterrole.yaml, twistlock-defender/templates/daemonset.yaml, twistlock-defender/templates/deployment.yaml, twistlock-defender/values.yaml
- Add `priorityClassName` to deployment.yaml
- Change `indent` to `nindent`
- Bump image tag to 20.04.163
- Update README
=> Add priorityClass to twistlock-console,defender and bump version

fluent-bit/Chart.yaml, fluent-bit/README.md, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
- fix bugs in https://github.com/chatwork/charts/pull/153
- `priorityClassName` is correct for `DaemonSet.spec.template.spec.priorityClassName` not `DaemonSet.spec.template.spec.container[].priorityClassName` 
- bump app version
- fix fluent.conf in values.yaml
- https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-parameters
=> fix fluent-bit

php/Chart.yaml, php/README.md, php/templates/deployment.yaml, php/templates/ingress.yaml, php/templates/service.yaml, php/values.yaml
Several resources supported changing labels and annotations.
Use cases are used for log transfers and operations.
=> [php] add labels and annotations

akka/.helmignore, akka/Chart.yaml, akka/Makefile, akka/README.md, akka/examples/cluster-discovery-aggregate.yaml, akka/examples/cluster-discovery-dns.yaml, akka/examples/cluster-discovery-kubernetes-api.yaml, akka/examples/cluster-multi-eks-cluster.yaml, akka/examples/local-akka-http.yaml, akka/examples/use-environment-variable-and-secret.yaml, akka/templates/NOTES.txt, akka/templates/_helpers.tpl, akka/templates/autoscaling.yaml, akka/templates/configmap.yaml, akka/templates/deployment.yaml, akka/templates/ingress-http.yaml, akka/templates/pdb.yaml, akka/templates/role.yaml, akka/templates/rolebinding.yaml, akka/templates/secret.yaml, akka/templates/service-http.yaml, akka/templates/service-management.yaml, akka/templates/serviceaccount.yaml, akka/templates/test/test-pod.yaml, akka/values.yaml
I have created a generic chart for the akka application.
At a minimum, we support akka configuration to work with chart.
We'll be supporting other settings from the next PR.
=> [akka] add chart

LICENSE, README.md
https://news-ja.chatwork.com/2018/11/new-mission.html
=> Fix corporate name in docs

postfix/Chart.yaml, postfix/templates/daemonset.yaml, postfix/templates/statefulset.yaml, postfix/values.yaml
=> [postfix] Add priorityClassName

postfix/Chart.yaml, postfix/templates/statefulset.yaml
=> [postfix] Modified chart indent

newrelic-php-agent/Chart.yaml, newrelic-php-agent/README.md, newrelic-php-agent/templates/daemonset.yaml, newrelic-php-agent/templates/deployment.yaml, newrelic-php-agent/values.yaml
=> [newrelic-php-agent] add resources

slime/Chart.yaml, slime/templates/configmap.yaml, slime/templates/deployment.yaml, slime/templates/secret.yaml, slime/templates/service.yaml, slime/values.yaml
- support for multiline annotation for deployment
- change `indent` to `nindent`
=> refactor slime

aws-alb-ingress-controller/Chart.yaml, aws-alb-ingress-controller/templates/deployment.yaml, aws-alb-ingress-controller/templates/pdb.yaml, aws-alb-ingress-controller/templates/psp.yaml, aws-alb-ingress-controller/templates/serviceaccount.yaml
=> [aws-alb-ingress-controller] fix bugs in chart

aws-alb-ingress-controller/Chart.yaml, aws-alb-ingress-controller/templates/pdb.yaml
- fix bugs in template for pdb
=> [aws-alb-ingress-controller] fixed bug

php/Chart.yaml, php/templates/ingress.yaml
Fixed `extraPaths` to be expanded `with`.
=> [php] fixes expand extraPaths

php/Chart.yaml, php/README.md, php/values.yaml
`serviceAccountName` and `readinessGates` have been fixed.
=> [php] fixes values & README.md

akka/Chart.yaml, akka/README.md, akka/templates/autoscaling.yaml, akka/templates/deployment.yaml, akka/values.yaml
- Fixed the parameters available from 1.18
=> [akka] Fixed the parameters available from 1.18

php/Chart.yaml, php/README.md, php/templates/autoscaling.yaml, php/templates/deployment.yaml, php/templates/ingress.yaml, php/values.yaml
Added support for new features in kubernetes v1.18.
- `autoscaling.behavior`
- `startupProbe`
- `ingress.ingressClassName`
=> [php] support kubernetes v1.18

aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/README.md, aws-ebs-csi-driver/templates/node.yaml, aws-ebs-csi-driver/values.yaml
- Modified bug for image pull policy
=> [aws-ebs-csi-driver] Modified image pull policy

fluent-bit/Chart.yaml, fluent-bit/templates/cluster-role.yaml, fluent-bit/values.yaml
- Add role
- https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/templates/clusterrole.yaml
- bump version
=> [fluent-bit]Add role

akka/Chart.yaml, akka/README.md
=> Fixed typo

aws-ebs-csi-driver/Chart.yaml, aws-ebs-csi-driver/README.md, aws-ebs-csi-driver/templates/controller.yaml, aws-ebs-csi-driver/templates/node.yaml, aws-ebs-csi-driver/values.yaml
- Add parameter to liveness-prove
- FYI: https://github.com/kubernetes-csi/livenessprobe/blob/master/deployment/kubernetes/livenessprobe-sidecar.yaml#L52
=> [aws-ebs-csi-driver]Add parameter to livenss-prove

raw/.helmignore, raw/Chart.yaml, raw/Makefile, raw/README.md, raw/ci.yaml, raw/templates/_helpers.tpl, raw/templates/resources.yaml, raw/templates/tests/test-pod.yaml, raw/values.yaml
This chart was copied from the following URL because it is no longer updated.
- https://github.com/helm/charts/tree/master/incubator/raw
=> add incubator/raw

metrics-server/.helmignore, metrics-server/Chart.yaml, metrics-server/Makefile, metrics-server/README.md, metrics-server/ci/ci-values.yaml, metrics-server/templates/NOTES.txt, metrics-server/templates/_helpers.tpl, metrics-server/templates/aggregated-metrics-reader-cluster-role.yaml, metrics-server/templates/auth-delegator-crb.yaml, metrics-server/templates/cluster-role.yaml, metrics-server/templates/metric-server-service.yaml, metrics-server/templates/metrics-api-service.yaml, metrics-server/templates/metrics-server-crb.yaml, metrics-server/templates/metrics-server-deployment.yaml, metrics-server/templates/metrics-server-serviceaccount.yaml, metrics-server/templates/pdb.yaml, metrics-server/templates/psp.yaml, metrics-server/templates/role-binding.yaml, metrics-server/templates/tests/test-version.yaml, metrics-server/values.yaml
This chart was copied from the following URL because it is no longer updated.
- https://github.com/helm/charts/tree/master/stable/metrics-server
=> add metrics-server

mysql/.helmignore, mysql/Chart.yaml, mysql/Makefile, mysql/README.md, mysql/templates/NOTES.txt, mysql/templates/_helpers.tpl, mysql/templates/configurationFiles-configmap.yaml, mysql/templates/deployment.yaml, mysql/templates/initializationFiles-configmap.yaml, mysql/templates/pvc.yaml, mysql/templates/secrets.yaml, mysql/templates/serviceaccount.yaml, mysql/templates/servicemonitor.yaml, mysql/templates/svc.yaml, mysql/templates/tests/test-configmap.yaml, mysql/templates/tests/test.yaml, mysql/values.yaml
This chart was copied from the following URL because it is no longer updated.
https://github.com/helm/charts/tree/master/stable/mysql
=> Add a mysql chart copied from `stable/mysql`

regcred/Chart.yaml, regcred/templates/secret.yaml
=> Modify secret resource name of regcred to fullname

.circleci/config.yml, Makefile
=> Set a CI context for notification

akka/Chart.yaml, akka/README.md, akka/templates/deployment.yaml, akka/values.yaml
Added exec to readiness/liveness/startup probe in akka chart.
=> [akka] Add exec to readiness/liveness/startup probe

akka/Chart.yaml, akka/templates/ingress-http.yaml
Fixed the problem of ingress being connected when multiple ingresses are defined.
=> [akka] Edit ingress 

metrics-server/Chart.yaml, metrics-server/README.md, metrics-server/templates/tests/test-version.yaml, metrics-server/values.yaml
- modify test annotation
- add toggle for test enable
=> [metrics-server]modify helm test

fluentd/Chart.yaml, fluentd/values.yaml
- change comment line in if section
=> [fluentd]modify fluentd config

fluent-bit/Chart.yaml, fluent-bit/README.md, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
- enable http port to change in values.yaml
- bump image tag
=> [fluent-bit]Add parameter for http port

postfix/Chart.yaml, postfix/Makefile, postfix/README.md, postfix/templates/daemonset.yaml, postfix/templates/deployment.yaml, postfix/templates/service.yaml, postfix/templates/statefulset.yaml, postfix/values.yaml
- bump postfix tag
- Add some parameters
=> Modify postfix

aws-secret-operator/Chart.yaml, aws-secret-operator/crds/crd.yaml
- fix CRD for https://github.com/mumoshu/aws-secret-operator/blob/master/deploy/crds/mumoshu.github.io_awssecrets.yaml
=> [aws-secret-operator]fix crd

postfix/Chart.yaml, postfix/README.md, postfix/templates/test/test-pod-mailcatcher.yaml, postfix/templates/test/test-pod.yaml, postfix/values.yaml
- set `hostNetwork` in daemonset to `false`
- FYI: https://github.com/chatwork/charts/pull/251
=> [postfix]set hostNetwork to false in values

php/Chart.yaml, php/templates/pdb.yaml
=> [php]fix pdb apiversion condition

twistlock-defender/Chart.yaml, twistlock-defender/README.md, twistlock-defender/templates/clusterrole.yaml, twistlock-defender/templates/daemonset.yaml, twistlock-defender/values.yaml
- update for 22.01.882 and cri
=> [twistlock-defender]update for 22.01.882 and cri

fluentd/Chart.yaml, fluentd/README.md, fluentd/templates/secret.yaml, fluentd/templates/statefulset.yaml, fluentd/values.yaml
https://github.com/chatwork/charts/pull/265
=> [fluentd]add envFrom and fix secrets

fluent-bit/Chart.yaml, fluent-bit/README.md, fluent-bit/templates/daemonset.yaml, fluent-bit/values.yaml
- bump fluent-bit
- fix `useKubelet` and add `useHostNetwork`
- https://github.com/fluent/fluent-bit/pull/5291
=> [fluent-bit]fix 'useKubelet' and add 'useHostNetwork'

aws-secret-operator/Chart.yaml
=> Bump appVersion to 0.5.2

php/Chart.yaml, php/templates/_helpers.tpl, php/templates/psp.yaml, php/templates/role.yaml
- remove Pod Security Policy because it is deprecated
=> [php]remove psp from kubernetes version 1.23

fluentd/Chart.yaml, fluentd/README.md, fluentd/templates/statefulset.yaml, fluentd/values.yaml
- Add `topologySpreadConstraints`
=> [fluentd]add topologySpreadConstraints

akka/Chart.yaml, akka/Makefile, akka/examples/local-akka-http.yaml, akka/templates/deployment.yaml, akka/values.yaml, php/Chart.yaml, php/templates/deployment.yaml, php/values.yaml, slime/Chart.yaml, slime/templates/deployment.yaml, slime/values.yaml
- change conditions for adding 'replicas' to allow for autoscaling features other than hpa
=> change deployment.spec.replicas condition

argoproj-crd/Chart.yaml, argoproj-crd/Makefile, argoproj-crd/ci.yaml, argoproj-crd/templates/_helpers.tpl, argoproj-crd/templates/appproject.yaml
- add sourceNamespaces in appproj
- https://github.com/argoproj/argo-helm/pull/1568/files#diff-b6b9d7ac0758942920be8788a5dd5d9f6748d8e5de30c51dd5687a02b5b52ccaR236
=> [argoproj-crd]add sourceNamespace in appproj

docker-registry/Chart.yaml, docker-registry/templates/configmap.yaml, docker-registry/templates/deployment.yaml, docker-registry/templates/ingress.yaml, docker-registry/templates/poddisruptionbudget.yaml, docker-registry/templates/pvc.yaml, docker-registry/templates/secret.yaml, docker-registry/templates/service.yaml, docker-registry/values.yaml
- bump apiVersion
- update depcated apiVersion
=> [docker-registry]fix deprecated api

burrow/Chart.yaml, burrow/Makefile, burrow/README.md, burrow/templates/deployment.yaml, burrow/values.yaml
- add `labels`, `podLabels`
- bump burrow
- update repositry
=> [burrow]update chart

burrow/Makefile
=> [burrow]update test

burrow/Chart.yaml, burrow/README.md
=> [burrow]update README

slime/Chart.yaml, slime/README.md
=> Fixed documentation for Slime's CronJob.

elasticmq/Chart.yaml, elasticmq/templates/test/test-pod.yaml, elasticmq/values.yaml
=> [elasticmq]add parameters to test

akka/Chart.yaml, akka/README.md, akka/templates/rollout.yaml, akka/values.yaml
=> add rollout

akka/Chart.yaml, akka/templates/rollout.yaml
Fixed the issue where ".Values" was missing.
=> Fix Rollout Field

akka/Chart.yaml, akka/templates/rollout.yaml
=> Remove trailing dash from if statement in template

newrelic-php-agent/Chart.yaml, newrelic-php-agent/templates/daemonset.yaml, newrelic-php-agent/values.yaml
=> [newrelic-php-agent]fix bug and bump tag

akka/Chart.yaml, akka/templates/autoscaling.yaml, akka/templates/rollout.yaml, akka/values.yaml
modification to allow the specification of scaleTargetRef to be something other than Deployment.
=> fix scaleTargetRef

akka/Chart.yaml, akka/templates/autoscaling.yaml
fix apiVersion of scaleTargetRef
=> fix apiVersion of scaleTargetRef

fluentd/Chart.yaml
=> [fluentd]bump appVersion

.github/workflows/publish.yml
=> fix publish ci

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
=> fix action condition

fluent-bit/Chart.yaml
=> Bump fluent bit

akka/Chart.yaml, akka/templates/autoscaling.yaml
=> fix as name

php/Chart.yaml, php/templates/deployment.yaml
https://chatwork.atlassian.net/browse/SREP-1678
=> Allow setting replicaCount to 0

akka/Chart.yaml, akka/README.md, akka/templates/autoscaling.yaml, akka/templates/deployment.yaml, akka/templates/statefulset.yaml, akka/values.yaml
https://chatwork.atlassian.net/browse/SPIC-1016
https://chatwork.atlassian.net/wiki/spaces/SP/pages/4146726093/SPIC-422+-+ID
=> Enables to use StatefulSet in akka

akka/Chart.yaml, akka/README.md, akka/templates/statefulset.yaml, akka/values.yaml
=> Enables to spicify annotations to statefulset.

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
Change workflow version to hash value
=> Change workflow version to hash value

Makefile, akka/Makefile, argoproj-crd/Makefile, aws-ebs-csi-driver/Makefile, aws-secret-operator/Makefile, burrow/Makefile, docker-registry/Makefile, dynamodb/Makefile, elasticmq/Makefile, elasticsearch/Makefile, envoy/Makefile, example/Makefile, fluent-bit/Makefile, fluentd/Makefile, gcp-credentials/Makefile, kube-schedule-scaler/Makefile, mailcatcher/Makefile, mysql/Makefile, newrelic-php-agent/Makefile, php/Makefile, postfix/Makefile, raw/Makefile, regcred/Makefile, slime/Makefile, twistlock-console/Makefile, twistlock-defender/Makefile
- kubernetes-json-schema locations temporarily
- target kubernetes version to 1.32.0
=> update kubernetes-json-schema repository url
